use serde::Deserialize;
use std::path::Path;

/// Runtime model configuration loaded from model_config.json.
/// Generated by helpers/gen_model_config.py from HuggingFace config.json.
/// No defaults — everything must come from the config file.
#[derive(Debug, Clone, Deserialize)]
pub struct ModelConfig {
    pub hidden_dim: usize,
    pub num_layers: usize,
    pub num_attn_heads: usize,
    pub num_kv_heads: usize,
    pub vocab_size: usize,
    pub num_experts: usize,
    pub num_experts_per_tok: usize,
    pub moe_intermediate: usize,
    pub shared_intermediate: usize,
    pub linear_num_v_heads: usize,
    pub linear_num_k_heads: usize,
    pub rotary_dim: usize,
    pub linear_total_key: usize,
    pub linear_total_value: usize,
    pub linear_conv_dim: usize,
    pub num_full_attn_layers: usize,
    pub num_linear_layers: usize,
    pub expert_size_4bit: usize,
    pub expert_size_2bit: usize,
    pub expert_layout_4bit: ExpertLayout,
    pub expert_layout_2bit: ExpertLayout,

    /// Populated at load time (not from JSON).
    #[serde(skip)]
    pub head_dim: usize,
    #[serde(skip)]
    pub group_size: usize,
    #[serde(skip)]
    pub bits: usize,
    #[serde(skip)]
    pub model_path: String,
}

/// Expert packed binary layout — offsets and sizes for each component.
#[derive(Debug, Clone, Deserialize)]
pub struct ExpertLayout {
    pub gate_w_off: usize,
    pub gate_s_off: usize,
    pub gate_b_off: usize,
    pub up_w_off: usize,
    pub up_s_off: usize,
    pub up_b_off: usize,
    pub down_w_off: usize,
    pub down_s_off: usize,
    pub down_b_off: usize,
    pub gate_w_size: usize,
    pub gate_s_size: usize,
    pub gate_b_size: usize,
    pub up_w_size: usize,
    pub up_s_size: usize,
    pub up_b_size: usize,
    pub down_w_size: usize,
    pub down_s_size: usize,
    pub down_b_size: usize,
}

/// Load model configuration from a model_config.json file.
pub fn load_model_config(model_path: &Path) -> anyhow::Result<ModelConfig> {
    let config_path = model_path.join("model_config.json");
    let content = std::fs::read_to_string(&config_path)?;
    let mut config: ModelConfig = serde_json::from_str(&content)?;
    config.head_dim = 256;
    config.group_size = 64;
    config.bits = 4;
    config.model_path = model_path.to_string_lossy().to_string();
    Ok(config)
}
