#!/usr/bin/env python3
"""Generate src/optimization.h with optimization feature flags.

Usage:
  python helpers/gen_optimizations.py                              # all disabled (default)
  python helpers/gen_optimizations.py --kv-bf16                    # enable KV cache bf16
  python helpers/gen_optimizations.py --fused-rms-norm             # enable fused RMS norm
  python helpers/gen_optimizations.py --event-pipeline             # enable MTLSharedEvent
  python helpers/gen_optimizations.py --cpu-fma                    # enable CPU FMA dequant
  python helpers/gen_optimizations.py --heap-topk                  # enable heap top-K
  python helpers/gen_optimizations.py --all                        # enable all
"""
import argparse
import os

TEMPLATE = """// Compile-time optimization feature flags
// Auto-generated by helpers/gen_optimizations.py — do not edit directly.
// Each flag gates an optimization independently. Set to 1 to enable, 0 to disable.
#ifndef OPTIMIZATION_H
#define OPTIMIZATION_H

// KV Cache bf16 quantization: halve memory bandwidth for full-attention layers.
// Switches KVCache storage from float to uint16_t (bfloat16).
// Affects: attention.h, layer_forward.h, shaders.metal, metal_setup.h
#define USE_KV_CACHE_BF16 {use_kv_cache_bf16}

// Fused RMS Norm Metal kernel: single-dispatch reduce+apply.
// Combines rms_norm_sum + rms_norm_apply into one kernel.
// Affects: shaders.metal (kernel), metal_setup.h (pipeline), layer_forward.h (usage)
#define USE_FUSED_RMS_NORM {use_fused_rms_norm}

// MTLSharedEvent async pipeline: non-blocking GPU completion check.
// GPU signals shared event on CMD3 commit; CPU checks signaledValue before blocking.
// Affects: layer_forward.h (encodeSignalEvent, signaledValue wait)
#define USE_EVENT_PIPELINE {use_event_pipeline}

// CPU dequant FMA variant: precomputed scale*x + bias*x with fmaf() intrinsics.
// Reduces inner-loop multiplies vs the base unrolled dequant matvec.
// Affects: cpu_kernels.h (cpu_dequant_matvec_fma), metal_setup.h (fallback path)
#define USE_CPU_DEQUANT_FMA {use_cpu_dequant_fma}

// Heap-based top-K: O(dim * log(K)) min-heap instead of O(dim * K) selection sort.
// With K=8, reduces comparisons by ~2.5x.
// Affects: cpu_kernels.h (cpu_topk)
#define USE_HEAP_TOPK {use_heap_topk}

#endif // OPTIMIZATION_H
"""


def generate(args):
    optimization_h = TEMPLATE.format(
        use_kv_cache_bf16=args.use_kv_cache_bf16,
        use_fused_rms_norm=args.use_fused_rms_norm,
        use_event_pipeline=args.use_event_pipeline,
        use_cpu_dequant_fma=args.use_cpu_dequant_fma,
        use_heap_topk=args.use_heap_topk,
    )

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo_root, "src", "optimization.h")

    # Only write if changed (avoids unnecessary rebuilds)
    if os.path.exists(out_path):
        with open(out_path) as f:
            if f.read() == optimization_h:
                print("optimization.h unchanged, skipping write")
                return out_path

    with open(out_path, "w") as f:
        f.write(optimization_h)
    print(f"Wrote {out_path}")
    return out_path


def main():
    parser = argparse.ArgumentParser(description="Generate src/optimization.h")

    parser.add_argument("--kv-bf16", action="store_true",
                        help="Enable KV cache bf16 quantization")
    parser.add_argument("--fused-rms-norm", action="store_true",
                        help="Enable fused RMS norm kernel")
    parser.add_argument("--event-pipeline", action="store_true",
                        help="Enable MTLSharedEvent async pipeline")
    parser.add_argument("--cpu-fma", action="store_true",
                        help="Enable CPU FMA dequant variant")
    parser.add_argument("--heap-topk", action="store_true",
                        help="Enable heap-based top-K")
    parser.add_argument("--all", action="store_true",
                        help="Enable all optimizations")

    args_raw = parser.parse_args()

    all_enabled = args_raw.all

    class Args:
        pass

    args = Args()
    args.use_kv_cache_bf16 = 1 if (args_raw.kv_bf16 or all_enabled) else 0
    args.use_fused_rms_norm = 1 if (args_raw.fused_rms_norm or all_enabled) else 0
    args.use_event_pipeline = 1 if (args_raw.event_pipeline or all_enabled) else 0
    args.use_cpu_dequant_fma = 1 if (args_raw.cpu_fma or all_enabled) else 0
    args.use_heap_topk = 1 if (args_raw.heap_topk or all_enabled) else 0

    out = generate(args)
    flags = [
        f"KV_BF16={args.use_kv_cache_bf16}",
        f"FUSED_RMS_NORM={args.use_fused_rms_norm}",
        f"EVENT_PIPELINE={args.use_event_pipeline}",
        f"CPU_FMA={args.use_cpu_dequant_fma}",
        f"HEAP_TOPK={args.use_heap_topk}",
    ]
    print(f"Optimizations: {', '.join(flags)}")


if __name__ == "__main__":
    main()
