#!/usr/bin/env python3
"""Generate src/config.h with the specified experiment configuration.

Usage:
  python helpers/gen_experiment.py --k 8 --cache-mode 0 --gpu-linear 1 --prediction 0
  python helpers/gen_experiment.py  # uses defaults
"""
import argparse
import os
import sys

TEMPLATE = """// Compile-time experiment configuration
// Auto-generated by helpers/gen_config.py — do not edit directly.
// Include is mandatory — infer.m will not compile without it.
#ifndef CONFIG_H
#define CONFIG_H

// Number of active experts per layer
#define NUM_ACTIVE_EXPERTS {active_experts}

// Expert cache: 0 = trust OS page cache, 1 = malloc cache
#define EXPERT_CACHE_MODE {expert_cache_mode}

// Number of malloc cache entries (only used when EXPERT_CACHE_MODE=1)
#define EXPERT_CACHE_ENTRIES {expert_cache_entries}

// Linear attention: 1 = fused GPU delta-net, 0 = CPU Accelerate BLAS
#define USE_GPU_LINEAR {use_gpu_linear}

// Expert prediction: 1 = enable, 0 = disable (paper: -18%, discarded)
#define USE_EXPERT_PREDICTION {use_expert_prediction}

// Weight loading: 1 = malloc+read, 0 = mmap
#define MALLOC_WEIGHTS {malloc_weights}

#endif // CONFIG_H
"""

DEFAULTS = {
    "active_experts": 8,
    "expert_cache_mode": 0,
    "expert_cache_entries": 0,
    "use_gpu_linear": 1,
    "use_expert_prediction": 0,
    "malloc_weights": 1,
}


def generate(args):
    config_h = TEMPLATE.format(
        active_experts=args.active_experts,
        expert_cache_mode=args.expert_cache_mode,
        expert_cache_entries=args.expert_cache_entries,
        use_gpu_linear=args.use_gpu_linear,
        use_expert_prediction=args.use_expert_prediction,
        malloc_weights=args.malloc_weights,
    )

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo_root, "src", "config.h")

    # Only write if changed (avoids unnecessary rebuilds)
    if os.path.exists(out_path):
        with open(out_path) as f:
            if f.read() == config_h:
                print(f"config.h unchanged, skipping write")
                return out_path

    with open(out_path, "w") as f:
        f.write(config_h)
    print(f"Wrote {out_path}")
    return out_path


def main():
    parser = argparse.ArgumentParser(description="Generate src/config.h")
    parser.add_argument("--active_experts", type=int, default=DEFAULTS["active_experts"],
                        help=f"Active experts per layer (default: {DEFAULTS['active_experts']})")
    parser.add_argument("--expert_cache_mode", type=int, default=DEFAULTS["expert_cache_mode"],
                        help=f"Expert cache: 0=OS page cache, 1=malloc (default: {DEFAULTS['expert_cache_mode']})")
    parser.add_argument("--expert_cache_entries", type=int, default=DEFAULTS["expert_cache_entries"],
                        help=f"Malloc cache entries (default: {DEFAULTS['expert_cache_entries']})")
    parser.add_argument("--use_gpu_linear", type=int, default=DEFAULTS["use_gpu_linear"],
                        help=f"GPU linear attention (default: {DEFAULTS['use_gpu_linear']})")
    parser.add_argument("--use_expert_prediction", type=int, default=DEFAULTS["use_expert_prediction"],
                        help=f"Expert prediction (default: {DEFAULTS['use_expert_prediction']})")
    parser.add_argument("--malloc_weights", type=int, default=DEFAULTS["malloc_weights"],
                        help=f"Malloc+read weights instead of mmap (default: {DEFAULTS['malloc_weights']})")
    args = parser.parse_args()
    out = generate(args)
    print(f"Config: active_experts={args.active_experts}, "
          f"expert_cache_mode={args.expert_cache_mode}, "
          f"use_gpu_linear={args.use_gpu_linear}, "
          f"use_expert_prediction={args.use_expert_prediction}, "
          f"malloc_weights={args.malloc_weights}")

if __name__ == "__main__":
    main()
