#!/usr/bin/env python3
"""Generate src/config.h with compile-time constants and experiment configuration.

Usage:
  python helpers/gen_config.py                                    # defaults
  python helpers/gen_config.py --active-experts 8 --kv-bf16 --heap-topk
  python helpers/gen_config.py --all                              # enable all optimizations
"""
import argparse
import os
import sys

TEMPLATE = """// Compile-time configuration — generated by helpers/gen_config.py.
// Do not edit directly.
#ifndef CONFIG_H
#define CONFIG_H

// ============================================================================
// Experiment configuration
// ============================================================================

#define NUM_ACTIVE_EXPERTS  {active_experts}
#define EXPERT_CACHE_MODE   {expert_cache_mode}
#define EXPERT_CACHE_ENTRIES {expert_cache_entries}
#define USE_GPU_LINEAR      {use_gpu_linear}
#define USE_EXPERT_PREDICTION {use_expert_prediction}
#define MALLOC_WEIGHTS      {malloc_weights}

// ============================================================================
// Optimization feature flags (1 = enabled, 0 = disabled)
// ============================================================================

#define USE_KV_CACHE_BF16       {use_kv_cache_bf16}
#define USE_FUSED_RMS_NORM      {use_fused_rms_norm}
#define USE_EVENT_PIPELINE      {use_event_pipeline}
#define USE_CPU_DEQUANT_FMA     {use_cpu_dequant_fma}
#define USE_HEAP_TOPK           {use_heap_topk}
#define USE_FUSED_GATE_UP_SWIGLU {use_fused_gate_up_swiglu}

// ============================================================================
// Compile-time constant — used in fixed-size stack array declarations.
// All other architectural values come from model_config.json at runtime.
// ============================================================================

#define MAX_K 8

#endif // CONFIG_H
"""

DEFAULTS = {
    "active_experts": 8,
    "expert_cache_mode": 0,
    "expert_cache_entries": 0,
    "use_gpu_linear": 1,
    "use_expert_prediction": 0,
    "malloc_weights": 1,
    "use_kv_cache_bf16": 1,
    "use_fused_rms_norm": 0,
    "use_event_pipeline": 0,
    "use_cpu_dequant_fma": 0,
    "use_heap_topk": 1,
    "use_fused_gate_up_swiglu": 0,
}


def _build_config(active_experts, expert_cache_mode, expert_cache_entries,
                  use_gpu_linear, use_expert_prediction, malloc_weights,
                  use_kv_cache_bf16, use_fused_rms_norm, use_event_pipeline,
                  use_cpu_dequant_fma, use_heap_topk, use_fused_gate_up_swiglu):
    return TEMPLATE.format(
        active_experts=active_experts,
        expert_cache_mode=expert_cache_mode,
        expert_cache_entries=expert_cache_entries,
        use_gpu_linear=use_gpu_linear,
        use_expert_prediction=use_expert_prediction,
        malloc_weights=malloc_weights,
        use_kv_cache_bf16=use_kv_cache_bf16,
        use_fused_rms_norm=use_fused_rms_norm,
        use_event_pipeline=use_event_pipeline,
        use_cpu_dequant_fma=use_cpu_dequant_fma,
        use_heap_topk=use_heap_topk,
        use_fused_gate_up_swiglu=use_fused_gate_up_swiglu,
    )


def _write_if_changed(out_path, config_h):
    if os.path.exists(out_path):
        with open(out_path) as f:
            if f.read() == config_h:
                print("config.h unchanged, skipping")
                return out_path
    with open(out_path, "w") as f:
        f.write(config_h)
    print(f"Wrote {out_path}")
    return out_path


def generate(args):
    config_h = _build_config(
        args.active_experts, args.expert_cache_mode, args.expert_cache_entries,
        args.use_gpu_linear, args.use_expert_prediction, args.malloc_weights,
        args.use_kv_cache_bf16, args.use_fused_rms_norm, args.use_event_pipeline,
        args.use_cpu_dequant_fma, args.use_heap_topk, args.use_fused_gate_up_swiglu,
    )

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo_root, "moe_infer", "core_src", "config.h")
    return _write_if_changed(out_path, config_h)


def generate_default():
    """Generate config.h with default values — called by setup.py."""
    args = type("Args", (), {})()
    for k, v in DEFAULTS.items():
        setattr(args, k.replace("-", "_"), v)
    config_h = _build_config(
        args.active_experts, args.expert_cache_mode, args.expert_cache_entries,
        args.use_gpu_linear, args.use_expert_prediction, args.malloc_weights,
        args.use_kv_cache_bf16, args.use_fused_rms_norm, args.use_event_pipeline,
        args.use_cpu_dequant_fma, args.use_heap_topk, args.use_fused_gate_up_swiglu,
    )
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo_root, "moe_infer", "core_src", "config.h")
    return _write_if_changed(out_path, config_h)


def main():
    parser = argparse.ArgumentParser(description="Generate src/config.h")
    parser.add_argument("--active-experts", type=int, default=DEFAULTS["active_experts"])
    parser.add_argument("--expert-cache-mode", type=int, default=DEFAULTS["expert_cache_mode"])
    parser.add_argument("--expert-cache-entries", type=int, default=DEFAULTS["expert_cache_entries"])
    parser.add_argument("--use-gpu-linear", type=int, default=DEFAULTS["use_gpu_linear"])
    parser.add_argument("--use-expert-prediction", type=int, default=DEFAULTS["use_expert_prediction"])
    parser.add_argument("--malloc-weights", type=int, default=DEFAULTS["malloc_weights"])
    parser.add_argument("--kv-bf16", action="store_true", help="KV cache bf16 quantization")
    parser.add_argument("--fused-rms-norm", action="store_true", help="Fused RMS norm kernel")
    parser.add_argument("--event-pipeline", action="store_true", help="MTLSharedEvent async pipeline")
    parser.add_argument("--cpu-fma", action="store_true", help="CPU FMA dequant")
    parser.add_argument("--heap-topk", action="store_true", help="Heap-based top-K")
    parser.add_argument("--fused-gate-up", action="store_true", help="Fused gate+up+SwiGLU kernel")
    parser.add_argument("--all", action="store_true", help="Enable all optimizations")
    args_raw = parser.parse_args()

    class Args: pass
    args = Args()
    all_en = args_raw.all
    args.active_experts = args_raw.active_experts
    args.expert_cache_mode = args_raw.expert_cache_mode
    args.expert_cache_entries = args_raw.expert_cache_entries
    args.use_gpu_linear = args_raw.use_gpu_linear
    args.use_expert_prediction = args_raw.use_expert_prediction
    args.malloc_weights = args_raw.malloc_weights
    args.use_kv_cache_bf16 = 1 if (args_raw.kv_bf16 or all_en) else 0
    args.use_fused_rms_norm = 1 if (args_raw.fused_rms_norm or all_en) else 0
    args.use_event_pipeline = 1 if (args_raw.event_pipeline or all_en) else 0
    args.use_cpu_dequant_fma = 1 if (args_raw.cpu_fma or all_en) else 0
    args.use_heap_topk = 1 if (args_raw.heap_topk or all_en) else 0
    args.use_fused_gate_up_swiglu = 1 if (args_raw.fused_gate_up or all_en) else 0

    out = generate(args)
    print(f"Config: active_experts={args.active_experts}, "
          f"KV_BF16={args.use_kv_cache_bf16}, HEAP_TOPK={args.use_heap_topk}, "
          f"GPU_LINEAR={args.use_gpu_linear}")

if __name__ == "__main__":
    main()
