// Compile-time configuration — generated by helpers/gen_config.py.
// Do not edit directly.
#ifndef CONFIG_H
#define CONFIG_H

// ============================================================================
// Experiment configuration
// ============================================================================

#define NUM_ACTIVE_EXPERTS  8
#define EXPERT_CACHE_MODE   0
#define EXPERT_CACHE_ENTRIES 0
#define USE_GPU_LINEAR      1
#define USE_EXPERT_PREDICTION 0
#define MALLOC_WEIGHTS      1

// ============================================================================
// Optimization feature flags (1 = enabled, 0 = disabled)
// ============================================================================

#define USE_KV_CACHE_BF16       1
#define USE_FUSED_RMS_NORM      0
#define USE_EVENT_PIPELINE      0
#define USE_CPU_DEQUANT_FMA     0
#define USE_HEAP_TOPK           1
#define USE_FUSED_GATE_UP_SWIGLU 0

// ============================================================================
// Architectural constants (same across all Qwen3 MoE models)
// ============================================================================

#define HEAD_DIM           256
#define GROUP_SIZE         64
#define BITS               4
#define RMS_NORM_EPS       1e-06f
#define ROPE_THETA         10000000.0f
#define PARTIAL_ROTARY     0.25f
#define FULL_ATTN_INTERVAL 4
#define CONV_KERNEL_SIZE   4
#define MAX_SEQ_LEN        1048576
#define GPU_KV_SEQ         8192
#define MAX_K              8
#define LINEAR_KEY_DIM     128
#define LINEAR_VALUE_DIM   128

#endif // CONFIG_H
