// Compile-time configuration — generated by helpers/gen_config.py.
// Do not edit directly.
#ifndef CONFIG_H
#define CONFIG_H

// ============================================================================
// Experiment configuration
// ============================================================================

#define NUM_ACTIVE_EXPERTS  8
#define EXPERT_CACHE_MODE   0
#define EXPERT_CACHE_ENTRIES 0
#define USE_GPU_LINEAR      1
#define USE_EXPERT_PREDICTION 0
#define MALLOC_WEIGHTS      1

// ============================================================================
// Optimization feature flags (1 = enabled, 0 = disabled)
// ============================================================================

#define USE_KV_CACHE_BF16       1
#define USE_FUSED_RMS_NORM      0
#define USE_EVENT_PIPELINE      0
#define USE_CPU_DEQUANT_FMA     0
#define USE_HEAP_TOPK           1
#define USE_FUSED_GATE_UP_SWIGLU 0

// ============================================================================
// Compile-time constant — used in fixed-size stack array declarations.
// All other architectural values come from model_config.json at runtime.
// ============================================================================

#define MAX_K 8

#endif // CONFIG_H
