// Auto-generated from shaders.metal — do not edit.
#ifndef SHADERS_H
#define SHADERS_H

static const char *g_shader_source =
"/*\n"
" * shaders.metal — Optimized Metal compute shaders for 4-bit quantized MoE inference\n"
" *\n"
" * Core operations:\n"
" *   1. dequant_matvec_4bit: Naive 4-bit affine dequant matvec (reference)\n"
" *   2. dequant_matvec_4bit_fast: SIMD-optimized with simd_sum reduction\n"
" *   3. dequant_matvec_4bit_v3: Fully optimized — tiled threadgroup, vector loads,\n"
" *      coalesced access, shared input cache.\n"
" *   4. swiglu_fused / swiglu_fused_vec4: SwiGLU activation\n"
" *   5. weighted_sum: combine expert outputs with routing weights\n"
" *   6. rms_norm: RMS normalization\n"
" *\n"
" * Quantization format (MLX affine 4-bit, group_size=64):\n"
" *   - Weights stored as uint32, each holding 8 x 4-bit values\n"
" *   - Per-group scale and bias in bfloat16\n"
" *   - Dequantized value = uint4_val * scale + bias\n"
" *   - Groups of 64 elements share one (scale, bias) pair\n"
" *\n"
" * Matrix layout for expert projections:\n"
" *   gate_proj/up_proj: [moe_intermediate, hidden/8] uint32 (out=moe_intermediate, in=hidden)\n"
" *   down_proj: [hidden, moe_intermediate/8] uint32 (out=hidden, in=moe_intermediate)\n"
" *\n"
" * All matrix dimensions are passed at runtime via constant buffers.\n"
" * MAX_INPUT_DIM = 4096: maximum supported hidden_dim for threadgroup shared memory.\n"
" */\n"
"\n"
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"// Maximum supported input dimension for threadgroup shared memory.\n"
"// Models with larger hidden_dim would need dynamic threadgroup memory.\n"
"#define MAX_INPUT_DIM 4096\n"
"\n"
"// ============================================================================\n"
"// BFloat16 helpers\n"
"// ============================================================================\n"
"\n"
"inline float bf16_to_f32(uint16_t bf16) {\n"
"    return as_type<float>(uint(bf16) << 16);\n"
"}\n"
"\n"
"inline uint16_t f32_to_bf16(float f) {\n"
"    return uint16_t(as_type<uint>(f) >> 16);\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 1: 4-bit dequantized matrix-vector multiply (NAIVE — reference)\n"
"// ============================================================================\n"
"\n"
"kernel void dequant_matvec_4bit(\n"
"    device const uint32_t* W_packed   [[buffer(0)]],\n"
"    device const uint16_t* scales     [[buffer(1)]],\n"
"    device const uint16_t* biases     [[buffer(2)]],\n"
"    device const float*    x          [[buffer(3)]],\n"
"    device float*          out        [[buffer(4)]],\n"
"    constant uint&         out_dim    [[buffer(5)]],\n"
"    constant uint&         in_dim     [[buffer(6)]],\n"
"    constant uint&         group_size [[buffer(7)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= out_dim) return;\n"
"\n"
"    uint num_groups = in_dim / group_size;\n"
"    uint packed_per_group = group_size / 8;\n"
"    uint packed_cols = in_dim / 8;\n"
"\n"
"    float acc = 0.0f;\n"
"\n"
"    device const uint32_t* w_row = W_packed + tid * packed_cols;\n"
"    device const uint16_t* s_row = scales + tid * num_groups;\n"
"    device const uint16_t* b_row = biases + tid * num_groups;\n"
"\n"
"    for (uint g = 0; g < num_groups; g++) {\n"
"        float scale = bf16_to_f32(s_row[g]);\n"
"        float bias  = bf16_to_f32(b_row[g]);\n"
"\n"
"        uint base_packed = g * packed_per_group;\n"
"        uint base_x = g * group_size;\n"
"\n"
"        for (uint p = 0; p < packed_per_group; p++) {\n"
"            uint32_t packed = w_row[base_packed + p];\n"
"            uint x_base = base_x + p * 8;\n"
"\n"
"            for (uint n = 0; n < 8; n++) {\n"
"                uint nibble = (packed >> (n * 4)) & 0xF;\n"
"                float w_val = float(nibble) * scale + bias;\n"
"                acc += w_val * x[x_base + n];\n"
"            }\n"
"        }\n"
"    }\n"
"\n"
"    out[tid] = acc;\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 1b: 4-bit dequant matvec — SIMD-optimized (legacy, kept for compat)\n"
"// ============================================================================\n"
"\n"
"kernel void dequant_matvec_4bit_fast(\n"
"    device const uint32_t* W_packed   [[buffer(0)]],\n"
"    device const uint16_t* scales     [[buffer(1)]],\n"
"    device const uint16_t* biases     [[buffer(2)]],\n"
"    device const float*    x          [[buffer(3)]],\n"
"    device float*          out        [[buffer(4)]],\n"
"    constant uint&         out_dim    [[buffer(5)]],\n"
"    constant uint&         in_dim     [[buffer(6)]],\n"
"    constant uint&         group_size [[buffer(7)]],\n"
"    uint tgid [[threadgroup_position_in_grid]],\n"
"    uint lid  [[thread_position_in_threadgroup]],\n"
"    uint tg_size [[threads_per_threadgroup]]\n"
") {\n"
"    if (tgid >= out_dim) return;\n"
"\n"
"    uint num_groups = in_dim / group_size;\n"
"    uint packed_per_group = group_size / 8;\n"
"    uint packed_cols = in_dim / 8;\n"
"\n"
"    device const uint32_t* w_row = W_packed + tgid * packed_cols;\n"
"    device const uint16_t* s_row = scales + tgid * num_groups;\n"
"    device const uint16_t* b_row = biases + tgid * num_groups;\n"
"\n"
"    float acc = 0.0f;\n"
"    for (uint g = lid; g < num_groups; g += tg_size) {\n"
"        float scale = bf16_to_f32(s_row[g]);\n"
"        float bias  = bf16_to_f32(b_row[g]);\n"
"\n"
"        uint base_packed = g * packed_per_group;\n"
"        uint base_x = g * group_size;\n"
"\n"
"        for (uint p = 0; p < packed_per_group; p++) {\n"
"            uint32_t packed = w_row[base_packed + p];\n"
"            uint x_base = base_x + p * 8;\n"
"\n"
"            acc += (float((packed >>  0) & 0xF) * scale + bias) * x[x_base + 0];\n"
"            acc += (float((packed >>  4) & 0xF) * scale + bias) * x[x_base + 1];\n"
"            acc += (float((packed >>  8) & 0xF) * scale + bias) * x[x_base + 2];\n"
"            acc += (float((packed >> 12) & 0xF) * scale + bias) * x[x_base + 3];\n"
"            acc += (float((packed >> 16) & 0xF) * scale + bias) * x[x_base + 4];\n"
"            acc += (float((packed >> 20) & 0xF) * scale + bias) * x[x_base + 5];\n"
"            acc += (float((packed >> 24) & 0xF) * scale + bias) * x[x_base + 6];\n"
"            acc += (float((packed >> 28) & 0xF) * scale + bias) * x[x_base + 7];\n"
"        }\n"
"    }\n"
"\n"
"    threadgroup float shared[32];\n"
"    float simd_val = simd_sum(acc);\n"
"\n"
"    uint simd_lane = lid % 32;\n"
"    uint simd_group = lid / 32;\n"
"    uint num_simd_groups = (tg_size + 31) / 32;\n"
"\n"
"    if (simd_lane == 0) {\n"
"        shared[simd_group] = simd_val;\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    if (simd_group == 0 && simd_lane < num_simd_groups) {\n"
"        float val = shared[simd_lane];\n"
"        val = simd_sum(val);\n"
"        if (simd_lane == 0) {\n"
"            out[tgid] = val;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"// ============================================================================\n"
"// Fused gate+up+SwiGLU: reads x ONCE, computes silu(gate(x)) * up(x)\n"
"// Saves one input read + one kernel dispatch per expert\n"
"// ============================================================================\n"
"kernel void fused_gate_up_swiglu(\n"
"    device const uint32_t* gate_W    [[buffer(0)]],\n"
"    device const uint16_t* gate_s    [[buffer(1)]],\n"
"    device const uint16_t* gate_b    [[buffer(2)]],\n"
"    device const uint32_t* up_W      [[buffer(3)]],\n"
"    device const uint16_t* up_s      [[buffer(4)]],\n"
"    device const uint16_t* up_b      [[buffer(5)]],\n"
"    device const float*    x         [[buffer(6)]],\n"
"    device float*          out       [[buffer(7)]],\n"
"    constant uint&         out_dim   [[buffer(8)]],\n"
"    constant uint&         in_dim    [[buffer(9)]],\n"
"    constant uint&         group_size [[buffer(10)]],\n"
"    uint tgid [[threadgroup_position_in_grid]],\n"
"    uint lid  [[thread_position_in_threadgroup]],\n"
"    uint tg_size [[threads_per_threadgroup]]\n"
") {\n"
"    if (tgid >= out_dim) return;\n"
"    uint num_groups = in_dim / group_size;\n"
"    uint packed_per_group = group_size / 8;\n"
"    uint packed_cols = in_dim / 8;\n"
"    device const uint32_t* gr = gate_W + tgid * packed_cols;\n"
"    device const uint16_t* gs = gate_s + tgid * num_groups;\n"
"    device const uint16_t* gb = gate_b + tgid * num_groups;\n"
"    device const uint32_t* ur = up_W   + tgid * packed_cols;\n"
"    device const uint16_t* us = up_s   + tgid * num_groups;\n"
"    device const uint16_t* ub = up_b   + tgid * num_groups;\n"
"    float ga = 0.0f, ua = 0.0f;\n"
"    for (uint g = lid; g < num_groups; g += tg_size) {\n"
"        float gsc = bf16_to_f32(gs[g]), gbi = bf16_to_f32(gb[g]);\n"
"        float usc = bf16_to_f32(us[g]), ubi = bf16_to_f32(ub[g]);\n"
"        uint bp = g * packed_per_group, bx = g * group_size;\n"
"        for (uint p = 0; p < packed_per_group; p++) {\n"
"            uint32_t gp = gr[bp+p], up = ur[bp+p];\n"
"            for (uint i = 0; i < 8; i++) {\n"
"                float xv = x[bx + p*8 + i];\n"
"                ga += (float((gp>>(i*4))&0xF)*gsc+gbi)*xv;\n"
"                ua += (float((up>>(i*4))&0xF)*usc+ubi)*xv;\n"
"            }\n"
"        }\n"
"    }\n"
"    threadgroup float sg[32], su[32];\n"
"    float rg = simd_sum(ga), ru = simd_sum(ua);\n"
"    uint sl = lid%32, si = lid/32, ns = (tg_size+31)/32;\n"
"    if (sl==0) { sg[si]=rg; su[si]=ru; }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    if (si==0 && sl<ns) {\n"
"        float vg=simd_sum(sg[sl]), vu=simd_sum(su[sl]);\n"
"        if (sl==0) out[tgid] = (vg/(1.0f+exp(-vg))) * vu;\n"
"    }\n"
"}\n"
"\n"
"// ============================================================================\n"
"// Kernel 1c: FULLY OPTIMIZED 4-bit dequant matvec\n"
"// ============================================================================\n"
"//\n"
"// Design for M3 Max (40-core GPU, SIMD width 32):\n"
"//\n"
"// Strategy: Each threadgroup handles ROWS_PER_TG output rows.\n"
"//   - Threadgroup size = 256 (8 SIMD groups of 32)\n"
"//   - Each SIMD group handles one output row\n"
"//   - Within a SIMD group, 32 threads split the input dimension\n"
"//   - Each thread processes in_dim/32 input elements using vector loads\n"
"//   - Reduction via simd_sum (single instruction)\n"
"//\n"
"// Memory optimizations:\n"
"//   - Input vector x cached in threadgroup shared memory (loaded once)\n"
"//   - uint4 vector loads for weights (128 bits = 32 nibbles per load)\n"
"//   - float4 vector loads for x (128 bits = 4 floats per load)\n"
"//   - Coalesced weight reads: adjacent threads read adjacent uint4 vectors\n"
"//\n"
"// For gate/up_proj [1024, 4096]: 1024/8 = 128 threadgroups, 256 threads each\n"
"//   - 128 * 256 = 32768 threads across 40 cores = good occupancy\n"
"//   - Each thread processes 4096/32 = 128 input elements = 16 uint32 packed words\n"
"//     = 4 uint4 loads per thread per row\n"
"//\n"
"// For down_proj [4096, 1024]: 4096/8 = 512 threadgroups\n"
"//   - Each thread processes 1024/32 = 32 input elements = 4 uint32 packed words\n"
"//     = 1 uint4 load per thread per row\n"
"\n"
"// Number of output rows per threadgroup = number of SIMD groups (256/32 = 8)\n"
"#define ROWS_PER_TG 8\n"
"\n"
"kernel void dequant_matvec_4bit_v3(\n"
"    device const uint32_t* W_packed   [[buffer(0)]],  // [out_dim, in_dim/8]\n"
"    device const uint16_t* scales     [[buffer(1)]],  // [out_dim, num_groups] bf16\n"
"    device const uint16_t* biases     [[buffer(2)]],  // [out_dim, num_groups] bf16\n"
"    device const float*    x          [[buffer(3)]],  // [in_dim]\n"
"    device float*          out        [[buffer(4)]],  // [out_dim]\n"
"    constant uint&         out_dim    [[buffer(5)]],\n"
"    constant uint&         in_dim     [[buffer(6)]],\n"
"    constant uint&         group_size [[buffer(7)]],\n"
"    uint tgid   [[threadgroup_position_in_grid]],     // which tile of rows\n"
"    uint lid    [[thread_position_in_threadgroup]],    // 0..255\n"
"    uint simd_lane  [[thread_index_in_simdgroup]],    // 0..31\n"
"    uint simd_group [[simdgroup_index_in_threadgroup]] // 0..7\n"
") {\n"
"    // Which output row this SIMD group handles\n"
"    uint row = tgid * ROWS_PER_TG + simd_group;\n"
"\n"
"    uint packed_cols = in_dim / 8;      // uint32 columns per row\n"
"    uint num_groups  = in_dim / group_size;\n"
"\n"
"    // ---- Cache input vector in threadgroup shared memory ----\n"
"    // Max in_dim = 4096, so we need 4096 floats = 16KB shared memory\n"
"    // This is well within the 32KB threadgroup memory limit on M3\n"
"    threadgroup float x_shared[MAX_INPUT_DIM];\n"
"\n"
"    // Cooperative load: 256 threads load 4096 floats (16 per thread)\n"
"    // ALL threads must participate in this load + barrier, even if their\n"
"    // row is out of bounds. Early return before the barrier causes only\n"
"    // partial loading of x_shared, corrupting results for valid rows.\n"
"    for (uint i = lid; i < in_dim; i += 256) {\n"
"        x_shared[i] = x[i];\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    // Now safe to bail out for out-of-bounds rows\n"
"    if (row >= out_dim) return;\n"
"\n"
"    // ---- Pointer setup for this row ----\n"
"    device const uint32_t* w_row = W_packed + row * packed_cols;\n"
"    device const uint16_t* s_row = scales + row * num_groups;\n"
"    device const uint16_t* b_row = biases + row * num_groups;\n"
"\n"
"    // ---- Each lane processes a strided slice of the packed columns ----\n"
"    // Lane k processes columns: k, k+32, k+64, ...\n"
"    // This gives coalesced reads: adjacent lanes read adjacent uint32 words.\n"
"\n"
"    float acc = 0.0f;\n"
"\n"
"    // Process packed columns in strides of 32 (one per SIMD lane)\n"
"    for (uint col = simd_lane; col < packed_cols; col += 32) {\n"
"        // Determine which group this column belongs to\n"
"        // packed_per_group = group_size / 8 = 64 / 8 = 8\n"
"        uint g = col / (group_size / 8);\n"
"        float scale = bf16_to_f32(s_row[g]);\n"
"        float bias  = bf16_to_f32(b_row[g]);\n"
"\n"
"        uint32_t packed = w_row[col];\n"
"        uint x_base = col * 8;\n"
"\n"
"        // Dequantize 8 nibbles and multiply with cached x\n"
"        // Rearranged: (nibble * scale + bias) * x = nibble * (scale*x) + bias*x\n"
"        // Pre-compute scale*x and bias*x, then use FMA for dequant+multiply in one op.\n"
"        // This reduces per-nibble from (convert + mul + add + mul + add) to (convert + FMA + add).\n"
"        float sx0 = scale * x_shared[x_base + 0];  float bx0 = bias * x_shared[x_base + 0];\n"
"        float sx1 = scale * x_shared[x_base + 1];  float bx1 = bias * x_shared[x_base + 1];\n"
"        float sx2 = scale * x_shared[x_base + 2];  float bx2 = bias * x_shared[x_base + 2];\n"
"        float sx3 = scale * x_shared[x_base + 3];  float bx3 = bias * x_shared[x_base + 3];\n"
"        float sx4 = scale * x_shared[x_base + 4];  float bx4 = bias * x_shared[x_base + 4];\n"
"        float sx5 = scale * x_shared[x_base + 5];  float bx5 = bias * x_shared[x_base + 5];\n"
"        float sx6 = scale * x_shared[x_base + 6];  float bx6 = bias * x_shared[x_base + 6];\n"
"        float sx7 = scale * x_shared[x_base + 7];  float bx7 = bias * x_shared[x_base + 7];\n"
"\n"
"        acc += fma(float((packed >>  0) & 0xF), sx0, bx0);\n"
"        acc += fma(float((packed >>  4) & 0xF), sx1, bx1);\n"
"        acc += fma(float((packed >>  8) & 0xF), sx2, bx2);\n"
"        acc += fma(float((packed >> 12) & 0xF), sx3, bx3);\n"
"        acc += fma(float((packed >> 16) & 0xF), sx4, bx4);\n"
"        acc += fma(float((packed >> 20) & 0xF), sx5, bx5);\n"
"        acc += fma(float((packed >> 24) & 0xF), sx6, bx6);\n"
"        acc += fma(float((packed >> 28) & 0xF), sx7, bx7);\n"
"    }\n"
"\n"
"    // ---- SIMD reduction: sum across 32 lanes ----\n"
"    float sum = simd_sum(acc);\n"
"\n"
"    // Lane 0 writes the result\n"
"    if (simd_lane == 0) {\n"
"        out[row] = sum;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 1f: 4-bit dequant matvec with LUT (eliminates uint→float conversions)\n"
"// ============================================================================\n"
"// Instead of converting each nibble to float (expensive conversion instruction),\n"
"// pre-compute a 16-entry LUT per group: lut[v] = float(v) * scale + bias.\n"
"// Then inner loop is just: acc += lut[nibble] * x_shared[i] — pure math, no conversions.\n"
"// The LUT is recomputed every group_size/8 iterations (amortized).\n"
"\n"
"#define ROWS_PER_TG_V5 8\n"
"\n"
"kernel void dequant_matvec_4bit_v5(\n"
"    device const uint32_t* W_packed   [[buffer(0)]],\n"
"    device const uint16_t* scales     [[buffer(1)]],\n"
"    device const uint16_t* biases     [[buffer(2)]],\n"
"    device const float*    x          [[buffer(3)]],\n"
"    device float*          out        [[buffer(4)]],\n"
"    constant uint&         out_dim    [[buffer(5)]],\n"
"    constant uint&         in_dim     [[buffer(6)]],\n"
"    constant uint&         group_size [[buffer(7)]],\n"
"    uint tgid   [[threadgroup_position_in_grid]],\n"
"    uint lid    [[thread_position_in_threadgroup]],\n"
"    uint simd_lane  [[thread_index_in_simdgroup]],\n"
"    uint simd_group [[simdgroup_index_in_threadgroup]]\n"
") {\n"
"    uint row = tgid * ROWS_PER_TG_V5 + simd_group;\n"
"    uint packed_cols = in_dim / 8;\n"
"    uint num_groups  = in_dim / group_size;\n"
"    uint packed_per_group = group_size / 8;\n"
"\n"
"    threadgroup float x_shared[MAX_INPUT_DIM];\n"
"    for (uint i = lid; i < in_dim; i += 256) {\n"
"        x_shared[i] = x[i];\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    if (row >= out_dim) return;\n"
"\n"
"    device const uint32_t* w_row = W_packed + row * packed_cols;\n"
"    device const uint16_t* s_row = scales + row * num_groups;\n"
"    device const uint16_t* b_row = biases + row * num_groups;\n"
"\n"
"    float acc = 0.0f;\n"
"    uint prev_g = 0xFFFFFFFF;\n"
"    float lut[16];\n"
"\n"
"    for (uint col = simd_lane; col < packed_cols; col += 32) {\n"
"        uint g = col / packed_per_group;\n"
"\n"
"        // Rebuild LUT when group changes\n"
"        if (g != prev_g) {\n"
"            float scale = bf16_to_f32(s_row[g]);\n"
"            float bias  = bf16_to_f32(b_row[g]);\n"
"            for (uint v = 0; v < 16; v++) {\n"
"                lut[v] = float(v) * scale + bias;\n"
"            }\n"
"            prev_g = g;\n"
"        }\n"
"\n"
"        uint32_t packed = w_row[col];\n"
"        uint x_base = col * 8;\n"
"\n"
"        acc += lut[(packed >>  0) & 0xF] * x_shared[x_base + 0];\n"
"        acc += lut[(packed >>  4) & 0xF] * x_shared[x_base + 1];\n"
"        acc += lut[(packed >>  8) & 0xF] * x_shared[x_base + 2];\n"
"        acc += lut[(packed >> 12) & 0xF] * x_shared[x_base + 3];\n"
"        acc += lut[(packed >> 16) & 0xF] * x_shared[x_base + 4];\n"
"        acc += lut[(packed >> 20) & 0xF] * x_shared[x_base + 5];\n"
"        acc += lut[(packed >> 24) & 0xF] * x_shared[x_base + 6];\n"
"        acc += lut[(packed >> 28) & 0xF] * x_shared[x_base + 7];\n"
"    }\n"
"\n"
"    float sum = simd_sum(acc);\n"
"    if (simd_lane == 0) {\n"
"        out[row] = sum;\n"
"    }\n"
"}\n"
"\n"
"// ============================================================================\n"
"// Kernel 1e: 2-bit affine dequant matvec (same structure as v3)\n"
"// ============================================================================\n"
"// Packs 16 x 2-bit values per uint32. Each value is 0-3, dequantized as:\n"
"//   val = uint2 * scale + bias (same affine quantization, just 2-bit range)\n"
"// Same group structure: group_size elements share one (scale, bias) pair.\n"
"// packed_cols = in_dim / 16 (16 values per uint32, vs 8 for 4-bit)\n"
"\n"
"kernel void dequant_matvec_2bit(\n"
"    device const uint32_t* W_packed   [[buffer(0)]],  // [out_dim, in_dim/16]\n"
"    device const uint16_t* scales     [[buffer(1)]],  // [out_dim, num_groups] bf16\n"
"    device const uint16_t* biases     [[buffer(2)]],  // [out_dim, num_groups] bf16\n"
"    device const float*    x          [[buffer(3)]],  // [in_dim]\n"
"    device float*          out        [[buffer(4)]],  // [out_dim]\n"
"    constant uint&         out_dim    [[buffer(5)]],\n"
"    constant uint&         in_dim     [[buffer(6)]],\n"
"    constant uint&         group_size [[buffer(7)]],\n"
"    uint tgid       [[threadgroup_position_in_grid]],\n"
"    uint lid        [[thread_position_in_threadgroup]],\n"
"    uint simd_lane  [[thread_index_in_simdgroup]],\n"
"    uint simd_group [[simdgroup_index_in_threadgroup]]\n"
") {\n"
"    uint row = tgid * ROWS_PER_TG + simd_group;\n"
"    uint packed_cols = in_dim / 16;  // 16 values per uint32 for 2-bit\n"
"    uint num_groups  = in_dim / group_size;\n"
"\n"
"    threadgroup float x_shared[MAX_INPUT_DIM];\n"
"    for (uint i = lid; i < in_dim; i += 256) {\n"
"        x_shared[i] = x[i];\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    if (row >= out_dim) return;\n"
"\n"
"    device const uint32_t* w_row = W_packed + row * packed_cols;\n"
"    device const uint16_t* s_row = scales + row * num_groups;\n"
"    device const uint16_t* b_row = biases + row * num_groups;\n"
"\n"
"    float acc = 0.0f;\n"
"\n"
"    // Each lane processes strided columns (16 values per uint32)\n"
"    for (uint col = simd_lane; col < packed_cols; col += 32) {\n"
"        // group_size/16 packed words per group\n"
"        uint g = col / (group_size / 16);\n"
"        float scale = bf16_to_f32(s_row[g]);\n"
"        float bias  = bf16_to_f32(b_row[g]);\n"
"\n"
"        uint32_t packed = w_row[col];\n"
"        uint x_base = col * 16;\n"
"\n"
"        // Unroll 16 x 2-bit extractions\n"
"        acc += (float((packed >>  0) & 0x3) * scale + bias) * x_shared[x_base +  0];\n"
"        acc += (float((packed >>  2) & 0x3) * scale + bias) * x_shared[x_base +  1];\n"
"        acc += (float((packed >>  4) & 0x3) * scale + bias) * x_shared[x_base +  2];\n"
"        acc += (float((packed >>  6) & 0x3) * scale + bias) * x_shared[x_base +  3];\n"
"        acc += (float((packed >>  8) & 0x3) * scale + bias) * x_shared[x_base +  4];\n"
"        acc += (float((packed >> 10) & 0x3) * scale + bias) * x_shared[x_base +  5];\n"
"        acc += (float((packed >> 12) & 0x3) * scale + bias) * x_shared[x_base +  6];\n"
"        acc += (float((packed >> 14) & 0x3) * scale + bias) * x_shared[x_base +  7];\n"
"        acc += (float((packed >> 16) & 0x3) * scale + bias) * x_shared[x_base +  8];\n"
"        acc += (float((packed >> 18) & 0x3) * scale + bias) * x_shared[x_base +  9];\n"
"        acc += (float((packed >> 20) & 0x3) * scale + bias) * x_shared[x_base + 10];\n"
"        acc += (float((packed >> 22) & 0x3) * scale + bias) * x_shared[x_base + 11];\n"
"        acc += (float((packed >> 24) & 0x3) * scale + bias) * x_shared[x_base + 12];\n"
"        acc += (float((packed >> 26) & 0x3) * scale + bias) * x_shared[x_base + 13];\n"
"        acc += (float((packed >> 28) & 0x3) * scale + bias) * x_shared[x_base + 14];\n"
"        acc += (float((packed >> 30) & 0x3) * scale + bias) * x_shared[x_base + 15];\n"
"    }\n"
"\n"
"    float sum = simd_sum(acc);\n"
"    if (simd_lane == 0) {\n"
"        out[row] = sum;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 1d: FULLY OPTIMIZED with uint4 vector loads\n"
"// ============================================================================\n"
"//\n"
"// Same structure as v3 but uses uint4 loads (128-bit / 16 bytes) to maximize\n"
"// memory bandwidth per thread. Each uint4 = 4 uint32 = 32 nibbles.\n"
"//\n"
"// For gate/up (packed_cols=512): each thread processes 512/32 = 16 uint32\n"
"//   = 4 uint4 loads per thread\n"
"// For down (packed_cols=128): each thread processes 128/32 = 4 uint32\n"
"//   = 1 uint4 load per thread\n"
"\n"
"kernel void dequant_matvec_4bit_v4(\n"
"    device const uint32_t* W_packed   [[buffer(0)]],\n"
"    device const uint16_t* scales     [[buffer(1)]],\n"
"    device const uint16_t* biases     [[buffer(2)]],\n"
"    device const float*    x          [[buffer(3)]],\n"
"    device float*          out        [[buffer(4)]],\n"
"    constant uint&         out_dim    [[buffer(5)]],\n"
"    constant uint&         in_dim     [[buffer(6)]],\n"
"    constant uint&         group_size [[buffer(7)]],\n"
"    uint tgid   [[threadgroup_position_in_grid]],\n"
"    uint lid    [[thread_position_in_threadgroup]],\n"
"    uint simd_lane  [[thread_index_in_simdgroup]],\n"
"    uint simd_group [[simdgroup_index_in_threadgroup]]\n"
") {\n"
"    uint row = tgid * ROWS_PER_TG + simd_group;\n"
"\n"
"    uint packed_cols = in_dim / 8;\n"
"    uint num_groups  = in_dim / group_size;\n"
"\n"
"    // Cache input vector — ALL threads must participate before the barrier\n"
"    threadgroup float x_shared[MAX_INPUT_DIM];\n"
"    for (uint i = lid; i < in_dim; i += 256) {\n"
"        x_shared[i] = x[i];\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    if (row >= out_dim) return;\n"
"\n"
"    // Pointers — cast to uint4 for vector loads\n"
"    device const uint4* w_row_v = (device const uint4*)(W_packed + row * packed_cols);\n"
"    device const uint16_t* s_row = scales + row * num_groups;\n"
"    device const uint16_t* b_row = biases + row * num_groups;\n"
"\n"
"    uint vec4_cols = packed_cols / 4;  // number of uint4 vectors per row\n"
"\n"
"    float acc = 0.0f;\n"
"\n"
"    // Each lane processes vec4_cols / 32 vectors (coalesced: adjacent lanes read adjacent uint4)\n"
"    for (uint vi = simd_lane; vi < vec4_cols; vi += 32) {\n"
"        uint4 packed4 = w_row_v[vi];\n"
"\n"
"        // Each uint4 covers 4 * 8 = 32 input elements\n"
"        // Starting packed column index = vi * 4\n"
"        uint base_col = vi * 4;\n"
"        uint x_base = base_col * 8;  // starting input element\n"
"\n"
"        // Process each of the 4 uint32 words in the uint4\n"
"        // Unroll all 4 words x 8 nibbles = 32 multiply-adds\n"
"        #pragma unroll\n"
"        for (uint w = 0; w < 4; w++) {\n"
"            uint32_t packed = packed4[w];\n"
"            uint col = base_col + w;\n"
"            uint g = col / (group_size / 8);\n"
"            float scale = bf16_to_f32(s_row[g]);\n"
"            float bias  = bf16_to_f32(b_row[g]);\n"
"\n"
"            uint xb = x_base + w * 8;\n"
"            acc += (float((packed >>  0) & 0xF) * scale + bias) * x_shared[xb + 0];\n"
"            acc += (float((packed >>  4) & 0xF) * scale + bias) * x_shared[xb + 1];\n"
"            acc += (float((packed >>  8) & 0xF) * scale + bias) * x_shared[xb + 2];\n"
"            acc += (float((packed >> 12) & 0xF) * scale + bias) * x_shared[xb + 3];\n"
"            acc += (float((packed >> 16) & 0xF) * scale + bias) * x_shared[xb + 4];\n"
"            acc += (float((packed >> 20) & 0xF) * scale + bias) * x_shared[xb + 5];\n"
"            acc += (float((packed >> 24) & 0xF) * scale + bias) * x_shared[xb + 6];\n"
"            acc += (float((packed >> 28) & 0xF) * scale + bias) * x_shared[xb + 7];\n"
"        }\n"
"    }\n"
"\n"
"    float sum = simd_sum(acc);\n"
"    if (simd_lane == 0) {\n"
"        out[row] = sum;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 1e: Multi-expert batched matvec\n"
"// ============================================================================\n"
"//\n"
"// Dispatch multiple experts simultaneously. The grid's Y dimension indexes\n"
"// the expert, so K experts' matmuls run as parallel threadgroups.\n"
"//\n"
"// Buffer layout: W_packed, scales, biases are arrays of K experts concatenated.\n"
"// x_inputs:  K input vectors concatenated [K * in_dim]\n"
"// out:       K output vectors concatenated [K * out_dim]\n"
"// expert_offsets: byte offset into W_packed buffer for each expert's weights\n"
"//                 (allows non-contiguous expert data in a shared buffer)\n"
"\n"
"kernel void dequant_matvec_4bit_batched(\n"
"    device const uint32_t* W_packed   [[buffer(0)]],\n"
"    device const uint16_t* scales     [[buffer(1)]],\n"
"    device const uint16_t* biases     [[buffer(2)]],\n"
"    device const float*    x_inputs   [[buffer(3)]],  // [K, in_dim]\n"
"    device float*          out        [[buffer(4)]],  // [K, out_dim]\n"
"    constant uint&         out_dim    [[buffer(5)]],\n"
"    constant uint&         in_dim     [[buffer(6)]],\n"
"    constant uint&         group_size [[buffer(7)]],\n"
"    // Per-expert offsets into the weight/scale/bias buffers (in elements)\n"
"    device const uint*     w_offsets  [[buffer(8)]],  // [K] offset in uint32 elements\n"
"    device const uint*     s_offsets  [[buffer(9)]],  // [K] offset in uint16 elements\n"
"    device const uint*     b_offsets  [[buffer(10)]], // [K] offset in uint16 elements\n"
"    constant uint&         num_row_tiles [[buffer(11)]], // ceil(out_dim / ROWS_PER_TG)\n"
"    uint tgid_flat [[threadgroup_position_in_grid]],  // linearized (row_tile + expert * num_row_tiles)\n"
"    uint lid       [[thread_position_in_threadgroup]],\n"
"    uint simd_lane  [[thread_index_in_simdgroup]],\n"
"    uint simd_group [[simdgroup_index_in_threadgroup]]\n"
") {\n"
"    // De-linearize: tgid_flat = row_tile + expert_k * num_row_tiles\n"
"    uint expert_k = tgid_flat / num_row_tiles;\n"
"    uint row_tile = tgid_flat % num_row_tiles;\n"
"    uint row = row_tile * ROWS_PER_TG + simd_group;\n"
"    if (row >= out_dim) return;\n"
"\n"
"    uint packed_cols = in_dim / 8;\n"
"    uint num_groups  = in_dim / group_size;\n"
"\n"
"    // Cache this expert's input vector\n"
"    threadgroup float x_shared[MAX_INPUT_DIM];\n"
"    device const float* x_k = x_inputs + expert_k * in_dim;\n"
"    for (uint i = lid; i < in_dim; i += 256) {\n"
"        x_shared[i] = x_k[i];\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    // Point to this expert's weights\n"
"    device const uint32_t* w_row = W_packed + w_offsets[expert_k] + row * packed_cols;\n"
"    device const uint16_t* s_row = scales   + s_offsets[expert_k] + row * num_groups;\n"
"    device const uint16_t* b_row = biases   + b_offsets[expert_k] + row * num_groups;\n"
"\n"
"    float acc = 0.0f;\n"
"\n"
"    for (uint col = simd_lane; col < packed_cols; col += 32) {\n"
"        uint g = col / (group_size / 8);\n"
"        float scale = bf16_to_f32(s_row[g]);\n"
"        float bias  = bf16_to_f32(b_row[g]);\n"
"\n"
"        uint32_t packed = w_row[col];\n"
"        uint x_base = col * 8;\n"
"\n"
"        acc += (float((packed >>  0) & 0xF) * scale + bias) * x_shared[x_base + 0];\n"
"        acc += (float((packed >>  4) & 0xF) * scale + bias) * x_shared[x_base + 1];\n"
"        acc += (float((packed >>  8) & 0xF) * scale + bias) * x_shared[x_base + 2];\n"
"        acc += (float((packed >> 12) & 0xF) * scale + bias) * x_shared[x_base + 3];\n"
"        acc += (float((packed >> 16) & 0xF) * scale + bias) * x_shared[x_base + 4];\n"
"        acc += (float((packed >> 20) & 0xF) * scale + bias) * x_shared[x_base + 5];\n"
"        acc += (float((packed >> 24) & 0xF) * scale + bias) * x_shared[x_base + 6];\n"
"        acc += (float((packed >> 28) & 0xF) * scale + bias) * x_shared[x_base + 7];\n"
"    }\n"
"\n"
"    float sum = simd_sum(acc);\n"
"    if (simd_lane == 0) {\n"
"        out[expert_k * out_dim + row] = sum;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 2: SwiGLU activation\n"
"// ============================================================================\n"
"\n"
"kernel void swiglu_fused(\n"
"    device const float* gate [[buffer(0)]],\n"
"    device const float* up   [[buffer(1)]],\n"
"    device float*       out  [[buffer(2)]],\n"
"    constant uint&      dim  [[buffer(3)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= dim) return;\n"
"\n"
"    float g = gate[tid];\n"
"    float silu_g = g / (1.0f + exp(-g));\n"
"    out[tid] = silu_g * up[tid];\n"
"}\n"
"\n"
"// Vectorized SwiGLU: process 4 elements per thread\n"
"kernel void swiglu_fused_vec4(\n"
"    device const float4* gate [[buffer(0)]],\n"
"    device const float4* up   [[buffer(1)]],\n"
"    device float4*       out  [[buffer(2)]],\n"
"    constant uint&       dim  [[buffer(3)]],  // original dim (must be multiple of 4)\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    uint vec_dim = dim / 4;\n"
"    if (tid >= vec_dim) return;\n"
"\n"
"    float4 g = gate[tid];\n"
"    float4 silu_g = g / (1.0f + exp(-g));\n"
"    out[tid] = silu_g * up[tid];\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 2b: Batched SwiGLU for K experts\n"
"// ============================================================================\n"
"\n"
"kernel void swiglu_fused_batched(\n"
"    device const float* gate [[buffer(0)]],  // [K * dim]\n"
"    device const float* up   [[buffer(1)]],  // [K * dim]\n"
"    device float*       out  [[buffer(2)]],  // [K * dim]\n"
"    constant uint&      dim  [[buffer(3)]],\n"
"    constant uint&      K    [[buffer(4)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    uint total = K * dim;\n"
"    if (tid >= total) return;\n"
"\n"
"    float g = gate[tid];\n"
"    float silu_g = g / (1.0f + exp(-g));\n"
"    out[tid] = silu_g * up[tid];\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 3: Weighted sum of expert outputs\n"
"// ============================================================================\n"
"\n"
"kernel void weighted_sum(\n"
"    device const float* expert_outs [[buffer(0)]],\n"
"    device const float* weights     [[buffer(1)]],\n"
"    device float*       out         [[buffer(2)]],\n"
"    constant uint&      K           [[buffer(3)]],\n"
"    constant uint&      dim         [[buffer(4)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= dim) return;\n"
"\n"
"    float acc = 0.0f;\n"
"    for (uint k = 0; k < K; k++) {\n"
"        acc += weights[k] * expert_outs[k * dim + tid];\n"
"    }\n"
"    out[tid] = acc;\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 4: RMS Normalization\n"
"// ============================================================================\n"
"\n"
"kernel void rms_norm_sum_sq(\n"
"    device const float* x       [[buffer(0)]],\n"
"    device float*       sum_sq  [[buffer(1)]],\n"
"    constant uint&      dim     [[buffer(2)]],\n"
"    uint tid  [[thread_position_in_grid]],\n"
"    uint lid  [[thread_position_in_threadgroup]],\n"
"    uint tg_size [[threads_per_threadgroup]]\n"
") {\n"
"    threadgroup float shared[32];\n"
"\n"
"    float acc = 0.0f;\n"
"    for (uint i = tid; i < dim; i += tg_size) {\n"
"        float val = x[i];\n"
"        acc += val * val;\n"
"    }\n"
"\n"
"    float simd_val = simd_sum(acc);\n"
"    uint simd_lane = lid % 32;\n"
"    uint simd_group = lid / 32;\n"
"\n"
"    if (simd_lane == 0) {\n"
"        shared[simd_group] = simd_val;\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    if (simd_group == 0) {\n"
"        float val = (simd_lane < (tg_size + 31) / 32) ? shared[simd_lane] : 0.0f;\n"
"        val = simd_sum(val);\n"
"        if (simd_lane == 0) {\n"
"            sum_sq[0] = val;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"kernel void rms_norm_apply(\n"
"    device const float* x       [[buffer(0)]],\n"
"    device const float* weight  [[buffer(1)]],\n"
"    device const float* sum_sq  [[buffer(2)]],\n"
"    device float*       out     [[buffer(3)]],\n"
"    constant uint&      dim     [[buffer(4)]],\n"
"    constant float&     eps     [[buffer(5)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= dim) return;\n"
"\n"
"    float rms = rsqrt(sum_sq[0] / float(dim) + eps);\n"
"    out[tid] = x[tid] * rms * weight[tid];\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 4b: RMS Normalization with bf16 weights\n"
"// ============================================================================\n"
"// Same as rms_norm_apply but reads weights as bfloat16 (uint16_t) and\n"
"// converts to float32 inline. Used in the fused o_proj+norm+routing path\n"
"// where norm weights come directly from the mmap'd weight file (bf16).\n"
"\n"
"kernel void rms_norm_apply_bf16(\n"
"    device const float*    x       [[buffer(0)]],\n"
"    device const uint16_t* weight  [[buffer(1)]],  // bf16 weights\n"
"    device const float*    sum_sq  [[buffer(2)]],\n"
"    device float*          out     [[buffer(3)]],\n"
"    constant uint&         dim     [[buffer(4)]],\n"
"    constant float&        eps     [[buffer(5)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= dim) return;\n"
"\n"
"    float rms = rsqrt(sum_sq[0] / float(dim) + eps);\n"
"    float w = bf16_to_f32(weight[tid]);\n"
"    out[tid] = x[tid] * rms * w;\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 4c: Fused RMS Normalization (single-kernel reduce+apply)\n"
"// ============================================================================\n"
"// Combines sum-of-squares reduction + apply in one dispatch with a threadgroup\n"
"// barrier. Saves one command buffer and one kernel dispatch vs the two-pass\n"
"// rms_norm_sum_sq + rms_norm_apply pattern.\n"
"//\n"
"// Dispatch: 1 threadgroup, 256 threads. Each thread processes dim/256 elements.\n"
"// Weight: bf16 (uint16_t), converted inline.\n"
"\n"
"#if USE_FUSED_RMS_NORM\n"
"kernel void rms_norm_fused(\n"
"    device const float*    x       [[buffer(0)]],\n"
"    device const uint16_t* weight  [[buffer(1)]],  // bf16 weights\n"
"    device float*          out     [[buffer(2)]],\n"
"    constant uint&         dim     [[buffer(3)]],\n"
"    constant float&        eps     [[buffer(4)]],\n"
"    uint tid  [[thread_position_in_grid]],\n"
"    uint lid  [[thread_position_in_threadgroup]],\n"
"    uint tg_size [[threads_per_threadgroup]]\n"
") {\n"
"    // Pass 1: sum of squares reduction\n"
"    threadgroup float shared_sum_sq[32];\n"
"\n"
"    float acc = 0.0f;\n"
"    for (uint i = tid; i < dim; i += tg_size) {\n"
"        float val = x[i];\n"
"        acc += val * val;\n"
"    }\n"
"\n"
"    float simd_val = simd_sum(acc);\n"
"    uint simd_lane = lid % 32;\n"
"    uint simd_group = lid / 32;\n"
"\n"
"    if (simd_lane == 0) {\n"
"        shared_sum_sq[simd_group] = simd_val;\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    threadgroup float tg_sum_sq;\n"
"    if (simd_group == 0) {\n"
"        float val = (simd_lane < (tg_size + 31) / 32) ? shared_sum_sq[simd_lane] : 0.0f;\n"
"        if (simd_lane == 0) {\n"
"            tg_sum_sq = simd_sum(val);\n"
"        }\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    float inv_rms = rsqrt(tg_sum_sq / float(dim) + eps);\n"
"\n"
"    // Pass 2: apply normalization\n"
"    for (uint i = tid; i < dim; i += tg_size) {\n"
"        float w = bf16_to_f32(weight[i]);\n"
"        out[i] = x[i] * inv_rms * w;\n"
"    }\n"
"}\n"
"#endif // USE_FUSED_RMS_NORM\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 5: Residual add\n"
"// ============================================================================\n"
"// out[i] = a[i] + b[i]\n"
"// Used to fuse the residual connection into a GPU command buffer,\n"
"// eliminating a CPU round-trip between o_proj and routing.\n"
"\n"
"kernel void residual_add(\n"
"    device const float* a   [[buffer(0)]],\n"
"    device const float* b   [[buffer(1)]],\n"
"    device float*       out [[buffer(2)]],\n"
"    constant uint&      dim [[buffer(3)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= dim) return;\n"
"    out[tid] = a[tid] + b[tid];\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 6: Batched GPU attention scores (Q @ K^T, scaled) — all heads at once\n"
"// ============================================================================\n"
"//\n"
"// Computes scores[h, p] = sum_d(Q[h, d] * K[p, kv_h*head_dim + d]) * scale\n"
"// for all heads h in [0, num_heads) and positions p in [0, seq_len).\n"
"//\n"
"// Grid: linearized (pos + h * num_seq_tgs) — one threadgroup per (position, head).\n"
"// Each threadgroup of 256 threads reduces over head_dim=256.\n"
"//\n"
"// GQA mapping: kv_head = h / heads_per_kv (e.g. 16 query heads share 1 KV head)\n"
"//\n"
"// Output layout: scores[h * seq_stride + p] where seq_stride = MAX_SEQ_LEN\n"
"\n"
"kernel void attn_scores_batched(\n"
"    device const float* Q          [[buffer(0)]],  // [num_heads, head_dim]\n"
"#if USE_KV_CACHE_BF16\n"
"    device const uint16_t* K_cache [[buffer(1)]],  // [max_seq, kv_dim] bf16\n"
"#else\n"
"    device const float* K_cache    [[buffer(1)]],  // [max_seq, kv_dim]\n"
"#endif\n"
"    device float*       scores     [[buffer(2)]],  // [num_heads, seq_stride]\n"
"    constant uint&      head_dim   [[buffer(3)]],  // 256\n"
"    constant uint&      kv_dim     [[buffer(4)]],  // 512\n"
"    constant uint&      seq_len    [[buffer(5)]],  // current seq length\n"
"    constant uint&      seq_stride [[buffer(6)]],  // MAX_SEQ_LEN\n"
"    constant float&     scale      [[buffer(7)]],  // 1/sqrt(head_dim)\n"
"    constant uint&      heads_per_kv [[buffer(8)]], // 16 (GQA ratio)\n"
"    constant uint&      num_seq_tgs  [[buffer(9)]],  // = seq_len\n"
"    uint tgid  [[threadgroup_position_in_grid]],    // linearized: pos + h * num_seq_tgs\n"
"    uint lid   [[thread_position_in_threadgroup]],\n"
"    uint tg_size [[threads_per_threadgroup]]\n"
") {\n"
"    uint pos = tgid % num_seq_tgs;\n"
"    uint h = tgid / num_seq_tgs;\n"
"    if (pos >= seq_len) return;\n"
"\n"
"    uint kv_h = h / heads_per_kv;\n"
"    device const float* qh = Q + h * head_dim;\n"
"#if USE_KV_CACHE_BF16\n"
"    device const uint16_t* kp = K_cache + pos * kv_dim + kv_h * head_dim;\n"
"#else\n"
"    device const float* kp = K_cache + pos * kv_dim + kv_h * head_dim;\n"
"#endif\n"
"\n"
"    float acc = 0.0f;\n"
"    for (uint d = lid; d < head_dim; d += tg_size) {\n"
"#if USE_KV_CACHE_BF16\n"
"        acc += qh[d] * bf16_to_f32(kp[d]);\n"
"#else\n"
"        acc += qh[d] * kp[d];\n"
"#endif\n"
"    }\n"
"\n"
"    // SIMD reduction\n"
"    float simd_val = simd_sum(acc);\n"
"    threadgroup float shared[32];\n"
"    uint simd_lane = lid % 32;\n"
"    uint simd_group = lid / 32;\n"
"    uint num_simd_groups = (tg_size + 31) / 32;\n"
"    if (simd_lane == 0) shared[simd_group] = simd_val;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    if (simd_group == 0 && simd_lane < num_simd_groups) {\n"
"        float val = simd_sum(shared[simd_lane]);\n"
"        if (simd_lane == 0) {\n"
"            scores[h * seq_stride + pos] = val * scale;\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 7: Batched softmax — one threadgroup per head\n"
"// ============================================================================\n"
"\n"
"kernel void attn_softmax_batched(\n"
"    device float*    scores     [[buffer(0)]],  // [num_heads, seq_stride]\n"
"    constant uint&   seq_len    [[buffer(1)]],\n"
"    constant uint&   seq_stride [[buffer(2)]],\n"
"    uint tgid [[threadgroup_position_in_grid]],     // head index\n"
"    uint lid  [[thread_position_in_threadgroup]],\n"
"    uint tg_size [[threads_per_threadgroup]]\n"
") {\n"
"    device float* s = scores + tgid * seq_stride;\n"
"\n"
"    // Pass 1: find max\n"
"    threadgroup float shared_max[32];\n"
"    float local_max = -1e30f;\n"
"    for (uint i = lid; i < seq_len; i += tg_size) {\n"
"        local_max = max(local_max, s[i]);\n"
"    }\n"
"    float sm = simd_max(local_max);\n"
"    uint simd_lane = lid % 32;\n"
"    uint simd_group = lid / 32;\n"
"    uint num_simd_groups = (tg_size + 31) / 32;\n"
"    if (simd_lane == 0) shared_max[simd_group] = sm;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    float global_max = -1e30f;\n"
"    if (simd_group == 0 && simd_lane < num_simd_groups) {\n"
"        global_max = simd_max(shared_max[simd_lane]);\n"
"    }\n"
"    threadgroup float broadcast_max;\n"
"    if (lid == 0) broadcast_max = global_max;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    global_max = broadcast_max;\n"
"\n"
"    // Pass 2: exp and sum\n"
"    threadgroup float shared_sum[32];\n"
"    float local_sum = 0.0f;\n"
"    for (uint i = lid; i < seq_len; i += tg_size) {\n"
"        float val = exp(s[i] - global_max);\n"
"        s[i] = val;\n"
"        local_sum += val;\n"
"    }\n"
"    float simd_s = simd_sum(local_sum);\n"
"    if (simd_lane == 0) shared_sum[simd_group] = simd_s;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    float global_sum = 0.0f;\n"
"    if (simd_group == 0 && simd_lane < num_simd_groups) {\n"
"        global_sum = simd_sum(shared_sum[simd_lane]);\n"
"    }\n"
"    threadgroup float broadcast_sum;\n"
"    if (lid == 0) broadcast_sum = global_sum;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    global_sum = broadcast_sum;\n"
"\n"
"    // Pass 3: normalize\n"
"    float inv_sum = 1.0f / global_sum;\n"
"    for (uint i = lid; i < seq_len; i += tg_size) {\n"
"        s[i] *= inv_sum;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 8: Batched attention value aggregation (scores @ V) — all heads\n"
"// ============================================================================\n"
"//\n"
"// For each head h: output[h*head_dim + d] = sum_p(scores[h*seq_stride+p] * V[p*kv_dim + kv_h*head_dim + d])\n"
"//\n"
"// Grid: linearized over (head_dim * num_heads) — one thread per (dimension, head).\n"
"\n"
"kernel void attn_values_batched(\n"
"    device const float* scores   [[buffer(0)]],  // [num_heads, seq_stride]\n"
"#if USE_KV_CACHE_BF16\n"
"    device const uint16_t* V_cache [[buffer(1)]],  // [max_seq, kv_dim] bf16\n"
"#else\n"
"    device const float* V_cache  [[buffer(1)]],  // [max_seq, kv_dim]\n"
"#endif\n"
"    device float*       out      [[buffer(2)]],  // [num_heads, head_dim]\n"
"    constant uint&      head_dim  [[buffer(3)]],  // 256\n"
"    constant uint&      kv_dim    [[buffer(4)]],  // 512\n"
"    constant uint&      seq_len   [[buffer(5)]],\n"
"    constant uint&      seq_stride [[buffer(6)]],\n"
"    constant uint&      heads_per_kv [[buffer(7)]],\n"
"    uint tid [[thread_position_in_grid]]          // linearized: d + h * head_dim\n"
") {\n"
"    uint d = tid % head_dim;\n"
"    uint h = tid / head_dim;\n"
"\n"
"    uint kv_h = h / heads_per_kv;\n"
"    device const float* s = scores + h * seq_stride;\n"
"\n"
"    float acc = 0.0f;\n"
"    for (uint p = 0; p < seq_len; p++) {\n"
"#if USE_KV_CACHE_BF16\n"
"        acc += s[p] * bf16_to_f32(V_cache[p * kv_dim + kv_h * head_dim + d]);\n"
"#else\n"
"        acc += s[p] * V_cache[p * kv_dim + kv_h * head_dim + d];\n"
"#endif\n"
"    }\n"
"    out[h * head_dim + d] = acc;\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 9: Sigmoid element-wise gate\n"
"// ============================================================================\n"
"// out[i] = x[i] * sigmoid(gate[i])\n"
"\n"
"kernel void sigmoid_gate(\n"
"    device float*       x_out  [[buffer(0)]],  // [dim] in/out\n"
"    device const float* gate   [[buffer(1)]],  // [dim] gate values\n"
"    constant uint&      dim    [[buffer(2)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= dim) return;\n"
"    float g = 1.0f / (1.0f + exp(-gate[tid]));\n"
"    x_out[tid] = x_out[tid] * g;\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 10: GatedDeltaNet linear attention step (single token, all heads)\n"
"// ============================================================================\n"
"//\n"
"// Implements the GatedDeltaNet recurrence for autoregressive generation:\n"
"//   1. State decay:  S[vi][ki] *= g_decay\n"
"//   2. Memory read:  kv_mem[vi] = sum_ki(S[vi][ki] * k[ki])\n"
"//   3. Delta:        delta[vi] = (v[vi] - kv_mem[vi]) * beta_gate\n"
"//   4. State update: S[vi][ki] += k[ki] * delta[vi]\n"
"//   5. Output:       out[vi] = sum_ki(S[vi][ki] * q[ki])\n"
"//\n"
"// Dispatch: 64 threadgroups (one per v-head), 128 threads each (one per vi).\n"
"// Each thread owns one row S[head_id][vi][:] of the 128x128 state matrix.\n"
"//\n"
"// State layout: [64 * 128 * 128] float = 4MB total, persisted across tokens.\n"
"// k-head sharing: 4 v-heads share 1 k-head (64 v-heads / 16 k-heads).\n"
"\n"
"kernel void gated_delta_net_step(\n"
"    device float *state,             // [64 * 128 * 128] persistent state\n"
"    device const float *q,           // [2048] (16 k-heads * 128)\n"
"    device const float *k,           // [2048] (16 k-heads * 128)\n"
"    device const float *v,           // [8192] (64 v-heads * 128)\n"
"    device const float *g_decay,     // [64] per v-head\n"
"    device const float *beta_gate,   // [64] per v-head\n"
"    device float *output,            // [8192] (64 v-heads * 128)\n"
"    constant uint &k_heads_per_v,    // = 4\n"
"    uint head_id [[threadgroup_position_in_grid]],\n"
"    uint vi [[thread_position_in_threadgroup]]\n"
") {\n"
"    uint kh = head_id / k_heads_per_v;\n"
"    float g = g_decay[head_id];\n"
"    float beta = beta_gate[head_id];\n"
"\n"
"    uint state_base = head_id * 128 * 128 + vi * 128;\n"
"    uint k_base = kh * 128;\n"
"    uint v_base = head_id * 128;\n"
"\n"
"    // Step 1+2: Decay state row and compute kv_mem = dot(S[vi][:], k[:])\n"
"    float kv_mem = 0.0f;\n"
"    for (uint ki = 0; ki < 128; ki++) {\n"
"        float s = state[state_base + ki] * g;\n"
"        state[state_base + ki] = s;\n"
"        kv_mem += s * k[k_base + ki];\n"
"    }\n"
"\n"
"    // Step 3+4: Delta update — S[vi][ki] += k[ki] * delta\n"
"    float delta = (v[v_base + vi] - kv_mem) * beta;\n"
"    for (uint ki = 0; ki < 128; ki++) {\n"
"        state[state_base + ki] += k[k_base + ki] * delta;\n"
"    }\n"
"\n"
"    // Step 5: Output — out[vi] = dot(S[vi][:], q[:])\n"
"    float out_val = 0.0f;\n"
"    for (uint ki = 0; ki < 128; ki++) {\n"
"        out_val += state[state_base + ki] * q[k_base + ki];\n"
"    }\n"
"    output[v_base + vi] = out_val;\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 11: Conv1d depthwise step (single token, incremental inference)\n"
"// ============================================================================\n"
"//\n"
"// Depthwise 1D convolution for one new input token:\n"
"//   output[c] = sum_k(history[k][c] * weight[c][k]) + input[c] * weight[c][3]\n"
"//   then SiLU activation: output[c] = output[c] / (1 + exp(-output[c]))\n"
"//\n"
"// After computing, shifts the history buffer left and appends the new input.\n"
"//\n"
"// Weight layout: [channels * kernel_size] bf16, weight[c * kernel_size + k]\n"
"// Conv state layout: [(kernel_size-1) * channels] row-major, state[k * channels + c]\n"
"// kernel_size = 4 (hardcoded), so 3 history slots + 1 new input.\n"
"//\n"
"// Dispatch: conv_dim threads (12288), one per channel.\n"
"\n"
"kernel void conv1d_step(\n"
"    device float *conv_state,         // [(kernel_size-1) * conv_dim] = [3 * conv_dim]\n"
"    device const float *input,        // [conv_dim] current input\n"
"    device const uint16_t *weights,   // [conv_dim * 4] bf16 as uint16\n"
"    device float *output,             // [conv_dim] convolution output\n"
"    constant uint &conv_dim,          // = 12288\n"
"    uint idx [[thread_position_in_grid]]\n"
") {\n"
"    if (idx >= conv_dim) return;\n"
"\n"
"    // Convolution: dot product of history + new input with weights\n"
"    // weight layout: weight[c * 4 + k] for channel c, position k\n"
"    uint w_base = idx * 4;\n"
"    float acc = 0.0f;\n"
"\n"
"    // 3 history slots (k=0,1,2)\n"
"    acc += conv_state[0 * conv_dim + idx] * bf16_to_f32(weights[w_base + 0]);\n"
"    acc += conv_state[1 * conv_dim + idx] * bf16_to_f32(weights[w_base + 1]);\n"
"    acc += conv_state[2 * conv_dim + idx] * bf16_to_f32(weights[w_base + 2]);\n"
"\n"
"    // New input (k=3)\n"
"    float inp = input[idx];\n"
"    acc += inp * bf16_to_f32(weights[w_base + 3]);\n"
"\n"
"    // SiLU activation\n"
"    output[idx] = acc / (1.0f + exp(-acc));\n"
"\n"
"    // Shift history: move slots 1,2 -> 0,1, append input at slot 2\n"
"    conv_state[0 * conv_dim + idx] = conv_state[1 * conv_dim + idx];\n"
"    conv_state[1 * conv_dim + idx] = conv_state[2 * conv_dim + idx];\n"
"    conv_state[2 * conv_dim + idx] = inp;\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 12: Per-head RMS normalize for q and k vectors\n"
"// ============================================================================\n"
"// q: [num_k_heads * key_dim], k: [num_k_heads * key_dim]\n"
"// Normalize each head independently, then scale by 1/sqrt(key_dim)^2 for q, 1/sqrt(key_dim) for k\n"
"// Dispatch: num_k_heads threadgroups, key_dim threads each\n"
"\n"
"kernel void rms_norm_qk(\n"
"    device float *q,              // [num_k_heads * key_dim] in/out\n"
"    device float *k,              // [num_k_heads * key_dim] in/out\n"
"    constant uint &key_dim,       // = 128\n"
"    constant float &inv_scale,    // = 1/sqrt(key_dim)\n"
"    uint head [[threadgroup_position_in_grid]],\n"
"    uint tid [[thread_position_in_threadgroup]]\n"
") {\n"
"    uint base = head * key_dim;\n"
"\n"
"    // RMS norm for q\n"
"    threadgroup float q_sum_sq;\n"
"    if (tid == 0) q_sum_sq = 0;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"\n"
"    float qval = (tid < key_dim) ? q[base + tid] : 0;\n"
"    // Use threadgroup atomic add for sum of squares\n"
"    float q_sq_local = qval * qval;\n"
"    // Simple reduction: thread 0 accumulates (key_dim=128, fits in one pass)\n"
"    threadgroup float q_partial[128];\n"
"    q_partial[tid] = q_sq_local;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    if (tid == 0) {\n"
"        float s = 0;\n"
"        for (uint i = 0; i < key_dim; i++) s += q_partial[i];\n"
"        q_sum_sq = s;\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    float q_inv_rms = rsqrt(q_sum_sq / float(key_dim) + 1e-6f);\n"
"    if (tid < key_dim) {\n"
"        q[base + tid] = qval * q_inv_rms * inv_scale * inv_scale;  // q gets extra scale\n"
"    }\n"
"\n"
"    // RMS norm for k\n"
"    threadgroup float k_sum_sq;\n"
"    float kval = (tid < key_dim) ? k[base + tid] : 0;\n"
"    threadgroup float k_partial[128];\n"
"    k_partial[tid] = kval * kval;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    if (tid == 0) {\n"
"        float s = 0;\n"
"        for (uint i = 0; i < key_dim; i++) s += k_partial[i];\n"
"        k_sum_sq = s;\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    float k_inv_rms = rsqrt(k_sum_sq / float(key_dim) + 1e-6f);\n"
"    if (tid < key_dim) {\n"
"        k[base + tid] = kval * k_inv_rms * inv_scale;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 13: Compute g_decay and beta_gate for GatedDeltaNet\n"
"// ============================================================================\n"
"// Per v-head: g_decay = exp(-A * softplus(alpha + dt_bias)), beta_gate = sigmoid(beta)\n"
"// Dispatch: num_v_heads threads (64)\n"
"\n"
"kernel void compute_decay_beta(\n"
"    device const float *alpha_out,   // [num_v_heads] from projection\n"
"    device const float *beta_out,    // [num_v_heads] from projection\n"
"    device const float *A_log,       // [num_v_heads] log of decay base (persistent)\n"
"    device const uint16_t *dt_bias,  // [num_v_heads] bf16\n"
"    device float *g_decay,           // [num_v_heads] output\n"
"    device float *beta_gate,         // [num_v_heads] output\n"
"    uint idx [[thread_position_in_grid]]\n"
") {\n"
"    float a_val = alpha_out[idx];\n"
"    float dt_b = bf16_to_f32(dt_bias[idx]);\n"
"    float A_val = exp(A_log[idx]);\n"
"    float softplus_val = log(1.0f + exp(a_val + dt_b));\n"
"    g_decay[idx] = exp(-A_val * softplus_val);\n"
"    beta_gate[idx] = 1.0f / (1.0f + exp(-beta_out[idx]));\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 14: Gated RMS norm (z-gated output normalization)\n"
"// ============================================================================\n"
"// output[i] = rms_norm(values[i]) * SiLU(z[i]) * weight[i]\n"
"// Per v-head: normalize values, gate with z, scale with weight\n"
"// Dispatch: num_v_heads threadgroups, value_dim threads each\n"
"\n"
"kernel void gated_rms_norm(\n"
"    device const float *values,       // [num_v_heads * value_dim] delta-net output\n"
"    device const float *z,            // [num_v_heads * value_dim] gate values\n"
"    device const uint16_t *weight,    // [value_dim] bf16 norm weights (shared across heads)\n"
"    device float *output,             // [num_v_heads * value_dim]\n"
"    constant uint &value_dim,         // = 128\n"
"    constant float &eps,              // = 1e-6\n"
"    uint head [[threadgroup_position_in_grid]],\n"
"    uint tid [[thread_position_in_threadgroup]]\n"
") {\n"
"    uint base = head * value_dim;\n"
"\n"
"    float val = (tid < value_dim) ? values[base + tid] : 0;\n"
"\n"
"    // RMS norm reduction\n"
"    threadgroup float partial[128];\n"
"    partial[tid] = val * val;\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    if (tid == 0) {\n"
"        float s = 0;\n"
"        for (uint i = 0; i < value_dim; i++) s += partial[i];\n"
"        partial[0] = s;\n"
"    }\n"
"    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
"    float inv_rms = rsqrt(partial[0] / float(value_dim) + eps);\n"
"\n"
"    if (tid < value_dim) {\n"
"        float normed = val * inv_rms;\n"
"        float zval = z[base + tid];\n"
"        float gate = zval / (1.0f + exp(-zval));  // SiLU\n"
"        float w = bf16_to_f32(weight[tid]);\n"
"        output[base + tid] = normed * gate * w;\n"
"    }\n"
"}\n"
"\n"
"\n"
"// ============================================================================\n"
"// Kernel 12: MoE combine + residual + shared expert gate (fused)\n"
"// ============================================================================\n"
"// Fused operation for CMD3 GPU-side combine:\n"
"//   hidden[i] = h_mid[i] + sum_k(expert_weight[k] * expert_out[k][i])\n"
"//               + sigmoid(shared_gate_score) * shared_out[i]\n"
"//\n"
"// All 8 expert output buffers are always bound (unused ones have weight=0).\n"
"// This avoids variable buffer bindings and keeps the dispatch simple.\n"
"//\n"
"// Dispatch: (dim + 255) / 256 threadgroups, 256 threads each.\n"
"\n"
"kernel void moe_combine_residual(\n"
"    device const float* h_mid       [[buffer(0)]],   // [dim]\n"
"    device const float* shared_out  [[buffer(1)]],   // [dim]\n"
"    device float*       hidden_out  [[buffer(2)]],   // [dim] output\n"
"    device const float* expert_out0 [[buffer(3)]],   // [dim] expert 0\n"
"    device const float* expert_out1 [[buffer(4)]],   // [dim] expert 1\n"
"    device const float* expert_out2 [[buffer(5)]],   // [dim] expert 2\n"
"    device const float* expert_out3 [[buffer(6)]],   // [dim] expert 3\n"
"    device const float* expert_out4 [[buffer(7)]],   // [dim] expert 4\n"
"    device const float* expert_out5 [[buffer(8)]],   // [dim] expert 5\n"
"    device const float* expert_out6 [[buffer(9)]],   // [dim] expert 6\n"
"    device const float* expert_out7 [[buffer(10)]],  // [dim] expert 7\n"
"    device const float* params      [[buffer(11)]],  // [10]: weights[0..7], shared_gate_score, (unused)\n"
"    constant uint&      dim         [[buffer(12)]],\n"
"    constant uint&      K           [[buffer(13)]],\n"
"    uint tid [[thread_position_in_grid]]\n"
") {\n"
"    if (tid >= dim) return;\n"
"\n"
"    // Read expert weights and shared gate from params buffer\n"
"    float shared_gate = 1.0f / (1.0f + exp(-params[8]));  // sigmoid(shared_gate_score)\n"
"\n"
"    // Weighted sum of expert outputs\n"
"    float moe = 0.0f;\n"
"    // Unrolled for MAX_K=8 with branch on K to avoid reading invalid buffers\n"
"    if (K > 0) moe += params[0] * expert_out0[tid];\n"
"    if (K > 1) moe += params[1] * expert_out1[tid];\n"
"    if (K > 2) moe += params[2] * expert_out2[tid];\n"
"    if (K > 3) moe += params[3] * expert_out3[tid];\n"
"    if (K > 4) moe += params[4] * expert_out4[tid];\n"
"    if (K > 5) moe += params[5] * expert_out5[tid];\n"
"    if (K > 6) moe += params[6] * expert_out6[tid];\n"
"    if (K > 7) moe += params[7] * expert_out7[tid];\n"
"\n"
"    hidden_out[tid] = h_mid[tid] + moe + shared_gate * shared_out[tid];\n"
"}\n"
;

#endif // SHADERS_H
