// Auto-generated by gen_model_config.py
// Model: Qwen3.5-35B-A3B
// Generated from config.json in: (source model directory)

#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

// ============================================================================
// Model dimensions
// ============================================================================

#define HIDDEN_DIM          2048
#define NUM_LAYERS          40
#define NUM_ATTN_HEADS      16
#define NUM_KV_HEADS        2
#define VOCAB_SIZE          248320
#define NUM_EXPERTS         256
#define NUM_EXPERTS_PER_TOK 8
#define MOE_INTERMEDIATE    512
#define SHARED_INTERMEDIATE 512

// ============================================================================
// Compile-time constants (same across all Qwen3.5 MoE models)
// ============================================================================

#define HEAD_DIM            256
#define GROUP_SIZE          64
#define BITS                4
#define RMS_NORM_EPS        1e-06f
#define ROPE_THETA          10000000.0f
#define PARTIAL_ROTARY      0.25f
#define ROTARY_DIM          64
#define FULL_ATTN_INTERVAL  4
#define CONV_KERNEL_SIZE    4
#define MAX_SEQ_LEN         1048576
#define GPU_KV_SEQ          8192
#define MAX_K               8

// ============================================================================
// Linear attention (GatedDeltaNet)
// ============================================================================

#define LINEAR_KEY_DIM      128
#define LINEAR_VALUE_DIM    128
#define LINEAR_NUM_V_HEADS  32
#define LINEAR_NUM_K_HEADS  16
#define LINEAR_TOTAL_KEY    2048
#define LINEAR_TOTAL_VALUE  4096
#define LINEAR_CONV_DIM     8192
#define NUM_FULL_ATTN_LAYERS 10
#define NUM_LINEAR_LAYERS   30

// ============================================================================
// 4-bit expert layout
// ============================================================================

#define EXPERT_SIZE         1769472
#define GATE_W_SIZE         524288
#define GATE_S_SIZE         32768
#define GATE_B_SIZE         32768
#define GATE_W_OFF          0
#define GATE_S_OFF          524288
#define GATE_B_OFF          557056
#define UP_W_SIZE           524288
#define UP_S_SIZE           32768
#define UP_B_SIZE           32768
#define UP_W_OFF            589824
#define UP_S_OFF            1114112
#define UP_B_OFF            1146880
#define DOWN_W_SIZE         524288
#define DOWN_S_SIZE         32768
#define DOWN_B_SIZE         32768
#define DOWN_W_OFF          1179648
#define DOWN_S_OFF          1703936
#define DOWN_B_OFF          1736704

// ============================================================================
// 2-bit expert layout
// ============================================================================

#define EXPERT_SIZE_2BIT    983040
#define GATE_W_SIZE_2       262144
#define GATE_S_SIZE_2       32768
#define GATE_B_SIZE_2       32768
#define GATE_W_OFF_2        0
#define GATE_S_OFF_2        262144
#define GATE_B_OFF_2        294912
#define UP_W_SIZE_2         262144
#define UP_S_SIZE_2         32768
#define UP_B_SIZE_2         32768
#define UP_W_OFF_2          327680
#define UP_S_OFF_2          589824
#define UP_B_OFF_2          622592
#define DOWN_W_SIZE_2       262144
#define DOWN_S_SIZE_2       32768
#define DOWN_B_SIZE_2       32768
#define DOWN_W_OFF_2        655360
#define DOWN_S_OFF_2        917504
#define DOWN_B_OFF_2        950272

// ============================================================================
// Special tokens
// ============================================================================

#define EOS_TOKEN_1         248046
#define EOS_TOKEN_2         248044
#define THINK_START_TOKEN   248068
#define THINK_END_TOKEN     248069

// ============================================================================
// Default model path
// ============================================================================

#define MODEL_PATH_DEFAULT "hub/models--mlx-community--Qwen3.5-35B-A3B-4bit"

#endif // MODEL_CONFIG_H
