// Compile-time experiment configuration
// Auto-generated by helpers/gen_experiment.py — do not edit directly.
// Include is mandatory — infer.m will not compile without it.
#ifndef CONFIG_H
#define CONFIG_H

// Active experts per layer
#define ACTIVE_EXPERTS_PER_LAYER 8

// Cache strategy: 0 = trust OS page cache, 1 = malloc expert cache
#define CACHE_MODE 0

// Number of malloc cache entries (only used when CACHE_MODE=1)
#define CACHE_ENTRIES 0

// Linear attention backend: 1 = fused GPU delta-net, 0 = CPU Accelerate BLAS
#define GPU_LINEAR 1

// Expert prediction: 1 = enable, 0 = disable (paper: -18%, discarded)
#define PREDICTION 0

#endif // CONFIG_H
