// Compile-time experiment configuration
// Auto-generated by helpers/gen_config.py — do not edit directly.
// Include is mandatory — infer.m will not compile without it.
#ifndef CONFIG_H
#define CONFIG_H

// Number of active experts per layer
#define NUM_ACTIVE_EXPERTS 8

// Expert cache: 0 = trust OS page cache, 1 = malloc cache
#define EXPERT_CACHE_MODE 0

// Number of malloc cache entries (only used when EXPERT_CACHE_MODE=1)
#define EXPERT_CACHE_ENTRIES 0

// Linear attention: 1 = fused GPU delta-net, 0 = CPU Accelerate BLAS
#define USE_GPU_LINEAR 1

// Expert prediction: 1 = enable, 0 = disable (paper: -18%, discarded)
#define USE_EXPERT_PREDICTION 0

// Weight loading: 1 = malloc+read, 0 = mmap
#define MALLOC_WEIGHTS 1

#endif // CONFIG_H
