// Compile-time optimization feature flags
// Auto-generated by helpers/gen_optimizations.py — do not edit directly.
// Each flag gates an optimization independently. Set to 1 to enable, 0 to disable.
#ifndef OPTIMIZATION_H
#define OPTIMIZATION_H

// KV Cache bf16 quantization: halve memory bandwidth for full-attention layers.
// Switches KVCache storage from float to uint16_t (bfloat16).
// Affects: attention.h, layer_forward.h, shaders.metal, metal_setup.h
#define USE_KV_CACHE_BF16 1

// Fused RMS Norm Metal kernel: single-dispatch reduce+apply.
// Combines rms_norm_sum + rms_norm_apply into one kernel.
// Affects: shaders.metal (kernel), metal_setup.h (pipeline), layer_forward.h (usage)
#define USE_FUSED_RMS_NORM 1

// MTLSharedEvent async pipeline: non-blocking GPU completion check.
// GPU signals shared event on CMD3 commit; CPU checks signaledValue before blocking.
// Affects: layer_forward.h (encodeSignalEvent, signaledValue wait)
#define USE_EVENT_PIPELINE 1

// CPU dequant FMA variant: precomputed scale*x + bias*x with fmaf() intrinsics.
// Reduces inner-loop multiplies vs the base unrolled dequant matvec.
// Affects: cpu_kernels.h (cpu_dequant_matvec_fma), metal_setup.h (fallback path)
#define USE_CPU_DEQUANT_FMA 1

// Heap-based top-K: O(dim * log(K)) min-heap instead of O(dim * K) selection sort.
// With K=8, reduces comparisons by ~2.5x.
// Affects: cpu_kernels.h (cpu_topk)
#define USE_HEAP_TOPK 1

#endif // OPTIMIZATION_H
